<h1><div class="icon"><i class="fa fa-info"></i></div>About Us</h1>

<ol class="breadcrumb">
	<li><a href="#home"><i class="fa fa-home"></i>Home</a></li>
	<li><i class="fa fa-info"></i>About</li>
</ol>

<p>Morgridge Software Assurance is committed to bringing a transformative change to the national software assurance landscape by providing continuous software assurance capabilities to researchers and developers. By providing software assurance researchers, tool developers, tool users and educators who train our workforce a suite of secure and dependable analysis services, we will help to reduce the number of vulnerabilities deployed in software.</p>

<p>Researchers who develop new software assurance tools and methodologies will use the repositories and cyberinfrastructure offered by the platform to improve their technologies and tools, while software developers and adopters will use the same services to hunt for vulnerabilities in their software. Educators will use these services to offer hands-on experience in software assurance techniques to their students.</p>

<p>By facilitating the sharing of tools, techniques, information, experiences and resources, we will:</p>
<ul>
	<li>Help advance the quality and adoption rate of software assurance tools;</li>
	<li>Lower the threshold for using them; and</li>
	<li>Make it easier to interpret and use the resulting output.</li>
</ul>

<h2>Why Use Software Assurance?</h2>
<p>Different people use these tools for different reasons. Why you participate depends on your goals.  Be assured that however you may choose to use the tools, you are in full control of your data.  You decide whether to make your results public or private or shared with just those you trust.</p>

<ul class="initial">
	<li>
		<h3>Software Developers</h3>
		use the the platform's range of software assurance tools to analyze their software. If they learn about a security weakness in their code, they can fix it.  Finding the weaknesses is the hard part. Manually reviewing code to find all the security weaknesses and vulnerabilities in software is tedious and labor-intensive job. Each operating system that runs their software can present new opportunities for security weaknesses. The platform automates finding the weaknesses in their code on multiple operating systems.
	</li>
	<li>
		<h3>SwA Tool Developers</h3>
		use the platform to help software developers assess their code. Developing static code analysis tools to automate the detection of security weaknesses and vulnerabilities is a great service to the software community at large!  But it is a challenging endeavor.  The platform makes their life easier with its wide assortment of software packages to test against and other tools to compare their tool against.
	</li>
	<li>
		<h3>Educators</h3>
		use the platform to help their Students learn about the importance of software assurance.  Many software developers do not use software assurance tools because either they are unaware of the available tools or they are too busy to learn how to use static code analysis tools effectively. The platform provides a one-stop shop equipped with the most instructive code examples and the best SwA tools for the most used programming languages. Plus, it makes training the next generation to use software assurance techniques available at no cost!
	</li>
	<li>
		<h3>IT Infrastructure Operators</h3>
		use the platform to improve their organization’s return on investment. No organization knowingly would put itself at risk operating with software having security vulnerabilities. Learning whether a piece of software is secure can be a time-consuming, expensive endeavor – especially considering all the software components in IT operations.  Organizations concerned with supply chain risk management find the platform a cost-effective means towards a sound software assurance policy.
	</li>
	<li>
		<h3>SwA Researchers</h3>
		use the platform as a laboratory for discovery.  It provides a big data center of software assessments generated by many SwA tools assessing hundreds of software packages on all common operating systems. The platform offers a nicely equipped laboratory to researchers at no cost.
	</li>
</ul>

<h2>The Team</h2>
<p>The project is led by a team at the <a href="http://www.morgridge.org" target="_blank">Morgridge Institute for Research</a> at the <a href="http://www.wisc.edu" target="_blank">University of Wisconsin, Madison</a>. </p>

<p>
	<label>Version:</label><span id="version"><%= version_string %></span><br />
	<label>API Base URL:</label><span id="server"><%= api_url %></span>
</p>
